In [17]:
import csv
with open(file="try.csv", mode="r") as f:
    # reader = csv.reader(f)
    reader = csv.DictReader(f)
    for row in reader:
        print(row)

{'Name': 'Ram', 'Address': 'Biratnagar', 'Age': '22'}
{'Name': 'Shyam', 'Address': 'Itahari', 'Age': '23'}
{'Name': 'Hari', 'Address': 'Dharan', 'Age': '21'}

In [18]:
import csv
with open(file="try.csv", mode="r") as f:
    reader = csv.reader(f)
    # reader = csv.DictReader(f)
    for row in reader:
        print(row)

['Name', 'Address', 'Age']
['Ram', 'Biratnagar', '22']
['Shyam', 'Itahari', '23']
['Hari', 'Dharan', '21']

In [19]:
import csv
data = [
    ['Name', 'Address', 'Age'],
    ['Ram', 'Biratnagar', '22'],
    ['Shyam', 'Itahari', '23'],
    ['Hari', 'Dharan', '21']
]

with open(file="new.csv",mode="w",newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

In [20]:
import csv
data = [
    {'Name': 'Ram', 'Address': 'Biratnagar', 'Age': '22'},
    {'Name': 'Shyam', 'Address': 'Itahari', 'Age': '23'},
    {'Name': 'Hari', 'Address': 'Dharan', 'Age': '21'},
]

with open(file='newnewnew.csv',mode="w",newline="") as f:
    writer = csv.DictWriter(f,fieldnames=["Name","Address","Age"])
    writer.writeheader()
    writer.writerows(data)

In [21]:
import pandas as pd

df = pd.read_csv("newnewnew.csv")
print(df)
print(type(df))

    Name     Address  Age
0    Ram  Biratnagar   22
1  Shyam     Itahari   23
2   Hari      Dharan   21
<class 'pandas.core.frame.DataFrame'>

In [22]:
df['Name']

0      Ram
1    Shyam
2     Hari
Name: Name, dtype: object

In [23]:
#Shows the information.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Address  3 non-null      object
 2   Age      3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [24]:
#view the data from top
df.head()
#view from tail

df.tail()

    Name     Address  Age
0    Ram  Biratnagar   22
1  Shyam     Itahari   23
2   Hari      Dharan   21

In [25]:
#view the random sample
df.sample()

    Name  Address  Age
1  Shyam  Itahari   23

In [26]:
#Check for the missing values
df.isnull().sum()

Name       0
Address    0
Age        0
dtype: int64

In [27]:
df['Province'] = "Koshi"

In [28]:
df.head()

    Name     Address  Age Province
0    Ram  Biratnagar   22    Koshi
1  Shyam     Itahari   23    Koshi
2   Hari      Dharan   21    Koshi

In [29]:
#Write csv
df.to_csv("neww.csv",index=False)

In [30]:
import pandas as pd

dataFrame = pd.DataFrame([
    {"Name":"Ram","Eng":80,"Math":81,"science":82},
    {"Name":"Shyam","Eng":79,"Math":80,"science":83},
])

dataFrame["Total"] = dataFrame["Eng"] + dataFrame["Math"] + dataFrame["science"]
dataFrame["Percentage"] = (dataFrame["Total"]/3).round(3)


dataFrame.to_csv("test.csv",index=False)
dataFrame

    Name  Eng  Math  science  Total  Percentage
0    Ram   80    81       82    243      81.000
1  Shyam   79    80       83    242      80.667

In [31]:
import json, pprint

with open("data.json","r") as f:
    data = json.load(f)

pprint.pprint(data)
print(data)

{'Name': 'Kayastha', 'skills': ['javascript', 'Python']}
{'Name': 'Kayastha', 'skills': ['javascript', 'Python']}

In [32]:
import json
data = {
     "Name":"Kayastha",
    "skills":["javascript","Python"]
}
with open("data1.json","w") as f:
    json.dump(data,f,indent=4
    )